minor fixes for new lod feature
symcon/VerbrauchZeitspanne pull request #11
Opened 2020-04-09 14:24 UTC by TillBrede

- no seconds hint when lod_date is selected
- check for AggregationStatus and Type
- usage = 0 if start == end or start  > end

2020-04-09 14:59 UTC, DrNiels requested changes

2020-04-09 14:59 UTC, DrNiels commented on VerbrauchZeitspanne/module.php
>                          echo $this->Translate('The seconds will be ignored.');
Ich würde die Sekunden auch bei LOD_DATE auf 0 setzen, nur kein echo ausgeben

2020-04-09 14:59 UTC, DrNiels commented on VerbrauchZeitspanne/module.php
> +            }
Funktionierten die besprochenen Ansätze mit $endDate um 1 reduzieren nicht?

2020-04-14 08:38 UTC, TillBrede commented on VerbrauchZeitspanne/module.php
> +            }
Der Check ist für bessere Lesbarkeit. 
$endDate - 1 wird aber noch eingebaut um das Zählen ungewollter Minuten zu verhindern

2020-04-14 11:30 UTC, merged