Added interval for calculation (PHP-126)
symcon/VerbrauchZeitspanne pull request #13
Opened 2020-05-19 14:56 UTC by TillBrede

2020-05-20 12:30 UTC, paresy requested changes
Sehr sehr cooler und ordentlicher PR!

Habe nur einen Mini Wunsch zur Optimierung :)

2020-05-20 12:30 UTC, paresy commented on VerbrauchZeitspanne/module.php
> +            $this->SetStatus(102);
Hier bitte noch ein GetStatus() != 102 einbauen, da ansonsten bei jedem Update der Status im ganzen System herumgeschickt wird :)

2020-05-31 07:27 UTC, paresy approved these changes

2020-07-01 12:59 UTC, DrNiels requested changes
Abgesehen von den zwei kleinen Anmerkungen sieht das super aus!

2020-07-01 12:59 UTC, DrNiels commented on tests/VerbrauchZeitspanneStatusTest.php
> +    public function testNotSelected(): void
Warum ist das ein testNotSelected? Da ist doch alles einwandfrei. Das hier ist für mich eher ein testActive oder dergleichen. Ein testNotSelected ist zusätzlich sicher aber auch schön

2020-07-01 12:59 UTC, DrNiels commented on VerbrauchZeitspanne/locale.json
> +			"No Source-Variable selected": "Keine Quellvariable ausgewählt",
Die Statusmeldung ist mit Punkt, daher wird sie nicht wie vorgesehen übersetzt

2020-07-17 10:55 UTC, DrNiels approved these changes

2020-07-17 10:55 UTC, merged