fixed usage of 0 if start equals end (PHP-168)
symcon/VerbrauchZeitspanne pull request #15
Opened 2020-12-10 09:04 UTC by TillBrede

2020-12-11 14:31 UTC, DrNiels commented
Das sieht soweit gut aus! Leider kann ich es gerade allerdings nicht im Module Control installieren... Sobald das klappt, teste ich noch einmal funktional und akzeptiere den PR dann wahrscheinlich.

Was mir noch aufgefallen ist, ist dass die Beschreibung im Ticket gar nicht zum PR passt. Ich vermute allerdings, dass @paresy hier unglücklich formuliert hat "Verbrauch in Zeitspanne läuft nur, wenn Start-Tag = End-Tag bei standard Detailstufe" klingt so, als wenn es nicht funktionieren würde, sobald Start und Ende verschieden sind.

2020-12-14 09:29 UTC, DrNiels requested changes
Ich erstelle eine Instanz und richte eine funktionierende Zählervariable (Typ Integer) als Quelle ein.   Ansonsten ändere ich nichts, also kein Intervall zum aktualisieren und Detailgrad bleibt bei Datum. Leider wird dann keine Verbrauchsvariable erstellt. Wenn ich versuche das Datum zu ändern, kommt nur eine Fehlermeldung, dass Usage ja nicht da ist. Das sollte so wohl nicht passieren.

2022-02-21 14:41 UTC, TillBrede commented
Konnte den Beschreibenen Fehler bisher nicht nachstellen

2022-03-09 09:29 UTC, paresy commented
Ich konnte den Fehler jetzt auch nicht nachstellen und der Rest sieht soweit ganz gut aus.

2022-03-09 09:30 UTC, merged